"""ChromaDB vector store wrapper.

This is the only module that talks to ChromaDB directly. It stores
pre-computed embeddings (generated by ``GeminiService``) alongside the
chunk text and metadata, and exposes a small, domain-oriented interface
to the rest of the application.
"""

import chromadb
from chromadb.config import Settings as ChromaSettings

from app.core.exceptions import VectorStoreError
from app.core.logging_config import get_logger
from app.models.domain import Chunk, RetrievedChunk

logger = get_logger(__name__)


class ChromaService:
    """Reusable wrapper around a persistent ChromaDB collection."""

    def __init__(self, persist_directory: str, collection_name: str) -> None:
        self._collection_name = collection_name
        try:
            self._client = chromadb.PersistentClient(
                path=persist_directory,
                settings=ChromaSettings(anonymized_telemetry=False),
            )
            self._collection = self._client.get_or_create_collection(
                name=collection_name,
                metadata={"hnsw:space": "cosine"},
            )
        except Exception as exc:  # noqa: BLE001
            raise VectorStoreError("Failed to initialize the vector store.") from exc

    def add_chunks(self, chunks: list[Chunk], embeddings: list[list[float]]) -> None:
        """Add a batch of chunks and their pre-computed embeddings to the store."""
        if len(chunks) != len(embeddings):
            raise VectorStoreError(
                "Number of chunks does not match number of embeddings."
            )
        if not chunks:
            return

        try:
            self._collection.add(
                ids=[chunk.chunk_id for chunk in chunks],
                embeddings=embeddings,
                documents=[chunk.text for chunk in chunks],
                metadatas=[chunk.to_metadata() for chunk in chunks],
            )
        except Exception as exc:  # noqa: BLE001
            raise VectorStoreError("Failed to add chunks to the vector store.") from exc

        logger.info("chunks_indexed count=%d filename=%s", len(chunks), chunks[0].filename)

    def query(self, query_embedding: list[float], top_k: int) -> list[RetrievedChunk]:
        """Return the top-k most similar chunks to the given query embedding."""
        try:
            results = self._collection.query(
                query_embeddings=[query_embedding],
                n_results=top_k,
            )
        except Exception as exc:  # noqa: BLE001
            raise VectorStoreError("Failed to query the vector store.") from exc

        retrieved: list[RetrievedChunk] = []
        ids = results.get("ids", [[]])[0]
        documents = results.get("documents", [[]])[0]
        metadatas = results.get("metadatas", [[]])[0]
        distances = results.get("distances", [[]])[0]

        for chunk_id, document, metadata, distance in zip(
            ids, documents, metadatas, distances
        ):
            # Chroma returns cosine distance; convert to a 0-1 similarity
            # score where 1.0 means identical, for a more intuitive API.
            similarity_score = max(0.0, 1.0 - distance)
            retrieved.append(
                RetrievedChunk(
                    chunk_id=chunk_id,
                    text=document,
                    filename=metadata.get("filename", "unknown"),
                    page_number=metadata.get("page_number", -1),
                    similarity_score=round(similarity_score, 4),
                    section_title=metadata.get("section_title") or None,
                )
            )

        return retrieved

    def list_documents(self) -> dict[str, dict]:
        """Return per-filename aggregate stats: chunk count and page count."""
        try:
            all_records = self._collection.get(include=["metadatas"])
        except Exception as exc:  # noqa: BLE001
            raise VectorStoreError("Failed to list documents from the vector store.") from exc

        documents: dict[str, dict] = {}
        for metadata in all_records.get("metadatas", []):
            filename = metadata.get("filename", "unknown")
            page_number = metadata.get("page_number", 0)
            upload_date = metadata.get("upload_date")

            entry = documents.setdefault(
                filename, {"chunk_count": 0, "pages": set(), "upload_date": upload_date}
            )
            entry["chunk_count"] += 1
            entry["pages"].add(page_number)

        return documents

    def delete_document(self, filename: str) -> int:
        """Delete all chunks belonging to the given filename. Returns count deleted."""
        try:
            matching = self._collection.get(where={"filename": filename}, include=[])
            ids_to_delete = matching.get("ids", [])
            if not ids_to_delete:
                return 0
            self._collection.delete(ids=ids_to_delete)
        except Exception as exc:  # noqa: BLE001
            raise VectorStoreError(f"Failed to delete document '{filename}'.") from exc

        logger.info("document_deleted filename=%s chunks_removed=%d", filename, len(ids_to_delete))
        return len(ids_to_delete)

    def total_chunk_count(self) -> int:
        """Return the total number of chunks currently stored."""
        try:
            return self._collection.count()
        except Exception as exc:  # noqa: BLE001
            raise VectorStoreError("Failed to count chunks in the vector store.") from exc

    def clear_all(self) -> tuple[int, int]:
        """Remove every indexed document from the vector store.

        Returns:
            A tuple of (documents_removed, chunks_removed), computed
            before the collection is wiped.
        """
        documents = self.list_documents()
        documents_removed = len(documents)
        chunks_removed = sum(info["chunk_count"] for info in documents.values())

        try:
            self._client.delete_collection(self._collection_name)
            self._collection = self._client.get_or_create_collection(
                name=self._collection_name,
                metadata={"hnsw:space": "cosine"},
            )
        except Exception as exc:  # noqa: BLE001
            raise VectorStoreError("Failed to clear the vector store.") from exc

        logger.info(
            "vector_store_cleared documents_removed=%d chunks_removed=%d",
            documents_removed,
            chunks_removed,
        )
        return documents_removed, chunks_removed

    def is_reachable(self) -> bool:
        """Lightweight health check for the vector store."""
        try:
            self._collection.count()
            return True
        except Exception:  # noqa: BLE001
            return False
